name: Publish website to aws
on:
  push:
    branches:
      - publish-website-to-aws

jobs:
  build-deploy:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Gulp
        run: npm install -g gulp-cli

      - name: Install other dependencies
        run: npm install

      - name: Build the website
        run: gulp web

      - name: Get commit hash
        run: COMMIT=$(git rev-parse HEAD)

      - name: Test comit
        run: echo $COMMIT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - name: Deploy site to S3 bucket
        run: aws s3 sync build/gh-pages/ "s3://test-zafir-pdf/$COMMIT/"
        

      
      

      
        